# Generated by Django 3.1.1 on 2020-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.TextField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('images', models.TextField(null=True)),
                ('last_updated', models.CharField(max_length=30)),
            ],
        ),
    ]
